name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: |
          python -m pytest

      - name: Package Lambda function
        run: zip -r lambda_function.zip lambda_function.py

      - name: Deploy Lambda function
        uses: appleboy/lambda-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-west-2
          function_name: lambda-example
          zip_file: lambda_function.zip
          handler: lambda_function.lambda_handler
          runtime: python3.8
          timeout: 30
